### ISSUE TITLE
Wrong include statements '#include "../eigen/Eigen"' in installed headers

### ISSUE THREAD

**Issue by yurivict** [Artelnics/opennn#114]
https://github.com/Artelnics/opennn/blob/master/opennn/metrics.h#L18

This file is installed into /usr/local/include/opennn/metrics.h
Eigen is installed in /usr/local/include/eigen3/Eigen

The Eigen documentation https://eigen.tuxfamily.org/dox/GettingStarted.html says that it should be included using statements like ```#include <Eigen/...>```

**Comment by shleym2000** [comment]
The directory structure of the project has <root>/**opennn**/ and <root>/**eigen**/ subdirectories.

It means that headers from files in **opennn** can refer to headers in foreign worker should with relative path "../eigen/....."

Why is your eigen ended up in a totally different /usr/local/include/**eigen3** directory?
Is it possible that you are trying to use a different eigen library, you installed from a different source on different occasion instead of the library provided as part of this project?

**Comment by yurivict** [comment]
> Why is your eigen ended up in a totally different /usr/local/include/eigen3 directory?

Eigen3 package is installed into the /usr/local base.

**Comment by shleym2000** [comment]
Sure it is. And it is a separate Eigen installation.

Meanwhile Eigen code is part of this package (Artelnics/opennn). I think you would do better if you would use this particular "embedded"  version of Eigen.

**Comment by yurivict** [comment]
>  I think you would do better if you would use this particular "embedded" version of Eigen.

This requires Eigen to be reinstalled again, because you include it this way in the installed version of headers. It's a bad idea to keep reinstalling Eigen when it is already installed.

**Comment by shleym2000** [comment]
The trick with Eigen is that it does not need to be installed at all.

There is no separate run-time modules.
No source code to compile separately from openn code.

It is all-headers library and as long as you copy the **entire** directory structure of this project (which includes _"eigen"_ sub-directory in it, all relative paths to Eigen in the include statements will work.

**Comment by yurivict** [comment]
> The trick with Eigen is that it does not need to be installed at all.

Eigen is always installed like all other dependencies, otherwise where does it come from.

**Comment by shleym2000** [comment]
If it is headers-only library (_Eigen_ here), it can come from sub-directory of the source code of the main package (_opennn_, in this case).

As a matter of fact, I would be concerned to use separately installed Eigen, because it might be a version _opennn_ is not tested to work with while the Eigen code in _opennn_'s own sub-directory is the one tested by _opennn_ developers.
