### ISSUE TITLE
Hello, seems the maximum function does not have a definition in the statistics.cpp file. Might this be the issue

### ISSUE THREAD

**Issue by herbertamukhuma** [Artelnics/opennn#160]
Hello, seems the maximum function does not have a definition in the statistics.cpp file. Might this be the issue
![IMG_20201016_130758](https://user-images.githubusercontent.com/37830837/96247205-7bc47500-0fb2-11eb-86fc-b062eb63f6b4.jpg)

_Originally posted by @herbertamukhuma in https://github.com/Artelnics/opennn/issue_comments/709958487_

**Comment by jandres-artelnics** [comment]
Hi @herbertamukhuma ,  

You're right and this function is not defined but we didn't noticed it since we don't use it. 

The funciton we're using is maximum using type (i.e. float) and not Index. 

If you're specially interested in using this function and since this is an open source library, I'd recommend you to create the function and make a pull request so we can include it into the library.

Since that should not be a compilining error for our examples I'll close the issue.

If you face some trouble making the function please contact us.

Thank you for using OpenNN.

**Comment by herbertamukhuma** [comment]
That function is actually being used, and that's what's causing a compilation error. Take a look at the image attached.
![IMG_20201019_113956](https://user-images.githubusercontent.com/37830837/96422103-4a40e900-1200-11eb-8de5-03d947cb2f4a.jpg)
