### ISSUE TITLE
That function is actually being used, and that's what's causing a compilation error. Take a look at the image attached.

### ISSUE THREAD

**Issue by herbertamukhuma** [Artelnics/opennn#161]
That function is actually being used, and that's what's causing a compilation error. Take a look at the image attached.
![IMG_20201019_113956](https://user-images.githubusercontent.com/37830837/96422103-4a40e900-1200-11eb-8de5-03d947cb2f4a.jpg)

_Originally posted by @herbertamukhuma in https://github.com/Artelnics/opennn/issue_comments/711861862_

**Comment by jandres-artelnics** [comment]
You're right.

Already fixed on dev. Can you try with dev if it works for you now?

Thank you.

**Comment by jandres-artelnics** [comment]
Hi @herbertamukhuma ,

you're right. I'll fix it. Thank you.

**Comment by jandres-artelnics** [comment]
Hi @herbertamukhuma , 

I added the maximum using Index in dev branch but it should not be a problem since it's defined with time_t and, inside, it's an integer too.

I added the maximum using index because it got to be there, but this should not be a compilation issue.

I cannot understand why are you keep on getting compilation errors.

Can you remove all temp files (from building) and try again? Or even deleting the whole project and cloning it again.

Thank you.

**Comment by jandres-artelnics** [comment]
Hi @herbertamukhuma , 

were you able to run OpenNN?

**Comment by herbertamukhuma** [comment]
The error was resolved, but then others followed 😭. Had to look for an alternative. You may close the issue.

**Comment by jandres-artelnics** [comment]
I'll close the issue and contact you via email to try to solve your problem.
