### ISSUE TITLE
Is it works on ARM machines with Debian Linux (NanoPi NEO: Allwinner H3 and Armbian Linux, exactly)?  

### ISSUE THREAD

**Issue by wyncze13** [Artelnics/OpenNN#19]
I want to build a robot with the mentioned setup, and question is will it work on that, or the library has some x86 or Windows specific parts?

**Comment by RoberLopez** [comment]
Hello,

OpenNN is standard C++ and it should compile everywhere.

Best regards

------------------------------
*Roberto Lopez*
*CEO - Artelnics*

Artificial Intelligence Techniques SL
Carretera de Madrid 13
37900 Santa Marta de Tormes
Salamanca (Spain)

Phone: +34 651 46 26 38
E-mail: robertolopez@artelnics.com
------------------------------

This message is for the designated recipient only and may contain
privileged, proprietary, or otherwise private information. If you have
received it in error, please notify the sender immediately and delete the
original. Any other use of the email by you is prohibited.

2017-01-19 17:32 GMT+01:00 wyncze13 <notifications@github.com>:
