### ISSUE TITLE
How to run tests?

### ISSUE THREAD

**Issue by aarlt** [Artelnics/OpenNN#83]
How to run the tests? Why is it an interactive program? I would like to just run all tests.
```
➜  build git:(master) ✗ tests/tests
Open Neural Networks Library. Test Suite Application.
Write test:
vector
matrix
...
suite
Test: vector
OpenNN Exception: Vector template.
void save(const string&) const method.
Cannot open vector data file.
```

**Comment by GuillermoArtelnics** [comment]
This mistake has been fixed. The problem was caused by the missing folder in the directory, where the files generated by the tests were saved.

It is an interactive program since the process of running all the tests is longer than running a single class. This allows more efficiency when testing changes in a single class.

Now, using the `suite` command you can run all the tests.

I hope to have helped you.
